languages:
  - en
assetDomain: static5.algorea.org
customAssetPath: /frontend/assets/pbl-prod/
fontPreloads:
  - //static5.algorea.org/frontend/assets/common/media/geist-v3-latin-regular.woff2
  - //static5.algorea.org/frontend/assets/common/media/geist-v3-latin-500.woff2
  - //static5.algorea.org/frontend/assets/common/media/geist-v3-latin-300.woff2
  - //static5.algorea.org/frontend/assets/common/media/geist-v3-latin-700.woff2
customHeadTags:
  - <script async src="https://b.probabl.ai/pb.min.js"></script>
customStyleFile: custom-style.css